Sprint 1/step 2
myr-irina/react-burger pull request #1
Opened 2023-01-14 19:36 UTC by myr-irina

Реализовала верстку, добавила функционал закрытия/открытия попапов, в т.ч по клику по оверлею и кнопке Esc.

2023-01-14 20:04 UTC, andryxxa93 requested changes
Проделана большая работа! Вы хорошо разобрались с функциональными компонентами, правильно используете useEffect и PropTypes.

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- Расписать типы полей ингредиента и использовать во всех компонентах, которые принимают ингредиенты.
- Добавить проверку успешности запроса.
- Элементы хедера должны быть ссылками, а не просто текстом.

Более подробно описание проблемы смотрите комментарии в pull request.

Что понравилось:
- Сделали отписку от слушателя.
- Реализовали закрытие модалки по ESC.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

Удачных правок!

2023-01-14 20:04 UTC, andryxxa93 commented on src/components/app/app.tsx
> +    fetch(BASE_URL)
**Надо исправить**
Добавьте проверку ответа сервера - res.ok:

Например:

```
.then(res => res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
```

иначе сейчас, если сервер ответи не кодом 2xx, а какой либо ошибкой (4xx, 5xx) мы не попадем в catch т.к. в этом случае fetch не выбрасывает ошибку, мы попытаемся отрисовать данные, хотя они не пришли, в итоге на попытке отрисовки несуществующих данных упадет все приложение

[https://learn.javascript.ru/fetch](https://learn.javascript.ru/fetch)

[https://developer.mozilla.org/en-US/docs/Web/API/Response/ok](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok)

Т.к. эта проверка нужна у всех запросов, лучше вынести её в отдельную функцию

```
const checkReponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};
```

`fetch(someUrl).then(checkReponse)`

2023-01-14 20:04 UTC, andryxxa93 commented on src/components/app/app.tsx
> +        console.log(e);
**Можно улучшить**
Console.log нужен только для процесса разработки, перед сдачей проекта его нужно удалять, иначе она будет загружать консоль ненужной, а возможно и приватной информацией. А ошибку лучше записывать в state и показывать пользователю, чтобы он понимал, что происходит.

2023-01-14 20:04 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor.jsx
> +  data: PropTypes.array.isRequired,
**Необходимо исправить**
Сейчас получается, что под `data` может быть массив любого содержания. Это не верно. Необходимо расписать ингредиент - удобно это сделать в отдельном файле и оттуда импортировать всюду куда нужно. В том числе сюда.

2023-01-14 20:04 UTC, andryxxa93 commented on src/components/modal/modal.jsx
> +      document.removeEventListener('keydown', onEscKeyClose);
**Отлично!**
Вы сделали отписку от слушателя, это позволит избежать утечек памяти.

2023-01-14 20:04 UTC, andryxxa93 commented on src/utils/data.js
> +export const data = [
**Можно лучше**
Если вы берете данные с сервера, то этот файл уже не нужен.

2023-01-14 20:04 UTC, andryxxa93 commented on src/components/app/app.tsx
> +      )}
**Можно лучше**
Использование модальных окон лучше вынести в те компоненты к которым это относится. Конкретно в `BurgerConstructor ` и `BurgerIngredients `.

2023-01-15 14:43 UTC, myr-irina commented on src/components/burger-constructor/burger-constructor.jsx
> +  data: PropTypes.array.isRequired,
done

2023-01-16 07:04 UTC, andryxxa93 approved these changes
Отлично! Все замечания учтены, вы отлично поработали. Ваша работа принята.
Желаю удачного продолжения обучения!

2023-01-19 12:13 UTC, merged